---
# dotfiles tasks for ansible-role-vim.

- name: Copy dotfiles into place.
  copy:
    src: "{{ dotfile }}"
    dest: "{{ vim_user_home_directory }}/{{ dotfile | basename }}"
    owner: "{{ vim_owner }}"
    group: "{{ vim_group }}"
  loop: "{{ vim_dotfiles }}"
  loop_control:
    loop_var: dotfile
