---
# helptags-related tasks for ansible-role-vim.

- name: Set the path to the to-be-generated tags file.
  set_fact:
    vim_tags_file_path: "{{ vim_plugin_parent_directory }}/tags"

- name: Create or modify Vim helptags.
  block:
    - name: Stat the original tags file--if it exists.
      stat:
        path: "{{ vim_tags_file_path }}"
      register: vim_tags_file_original
      changed_when: false

    - name: Generate or update helptags for Vim-related packages.
      command: "vim -c 'helptags .' -c q"
      args:
        chdir: "{{ vim_plugin_parent_directory }}"
      changed_when: false

    - name: Stat the tags file to find out when it was last modified.
      stat:
        path: "{{ vim_tags_file_path }}"
      register: vim_tags_file_updated
      failed_when: "not vim_tags_file_updated.stat.exists"
      changed_when: >
        not vim_tags_file_original.stat.exists and vim_tags_file_updated.stat.exists
        or vim_tags_file_updated.stat.checksum != vim_tags_file_original.stat.checksum

    - name: Set permissions on tags file.
      file:
        path: "{{ vim_tags_file_path }}"
        owner: "{{ vim_owner }}"
        group: "{{ vim_group }}"
        state: file
      when: "vim_tags_file_updated.stat.exists"
