---
# plugin installation tasks for ansible-role-vim.

- name: Install {{ plugin_data.type }} plugins.
  git:
    repo: "{{ plugin.repo }}"
    dest: "{{ vim_plugin_parent_directory }}/{{ plugin_data.directory }}/{{ (plugin.repo | basename | splitext)[0] }}"
    version: "{{ plugin.version | default('HEAD') }}"
    clone: true
  loop: "{{ plugin_data.list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest
