---
# tasks file for ansible-role-vim

- name: Determine home directory.
  set_fact:
    vim_home_directory: "{{ (ansible_system == 'Darwin') | ternary('Users', 'home') }}"

- name: Determine user home directory.
  set_fact:
    vim_user_home_directory: "/{{ vim_home_directory }}/{{ vim_owner }}"

- name: Remove unneeded Vim-related packages.
  package:
    name: "{{ vim_removed_packages }}"
    state: absent

- name: Install required Vim and Vim-related packages.
  package:
    name: "{{ vim_installed_packages }}"
    state: present

- name: Prepare install directories.
  file:
    path: "{{ vim_user_home_directory }}/{{ vim_directory }}"
    state: directory
    owner: "{{ vim_owner }}"
    group: "{{ vim_group }}"
  loop:
    - "{{ vim_pack_subdirectory }}"
    - "{{ vim_pack_subdirectory }}/start"
    - "{{ vim_pack_subdirectory }}/opt"
  loop_control:
    loop_var: vim_directory
