---
# package-related tasks for ansible-role-vim.

- name: Remove unneeded Vim-related packages.
  ansible.builtin.package:
    name: "{{ vim_removed_packages }}"
    state: absent

- name: Install required Vim and Vim-related packages.
  ansible.builtin.package:
    name: "{{ vim_installed_packages }}"
    state: present
