---
# Vim plugin removal for ansible-role-vim.
#
# Removes a single plugin.

- name: Determine '{{ vim_plugin_remove.directory }}' plugin install directory.
  ansible.builtin.set_fact:
    vim_plugin_path: "{{ vim_plugin_parent_directory }}/{{ vim_pack_subdirectory }}/{{ vim_plugin_remove.type }}/{{ vim_plugin_remove.directory }}"

- name: Remove '{{ vim_plugin_remove.directory }}' plugin.
  ansible.builtin.file:
    path: "{{ vim_plugin_path }}"
    state: absent
  register: vim_plugin_remove
