---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2004}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../converge.yml
    verify: ../verify.yml
scenario:
  name: default
  test_sequence:
    - create
    - prepare
    - converge
    #- idempotence
    - verify
    - destroy
verifier:
  name: ansible
  directory: ../tests/
