---
- name: Converge
  hosts: all
  vars:
    vim_removed_packages:
      - "vim-tiny"
    vim_owner: "lorem"
    vim_group: "lorem"
    vim_start_plugins:
      - repo: "https://github.com/altercation/vim-colors-solarized.git"
      - repo: "https://github.com/itchyny/lightline.vim.git"
    vim_opt_plugins:
      - repo: "https://github.com/vim-vdebug/vdebug.git"
  roles:
    - role: ansible-role-vim
