---
on: push

jobs:
  molecule:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.5
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - uses: gofrolist/molecule-action@v2
